### ISSUE TITLE
Create script to publish extension for beta-testing

### ISSUE THREAD

**Issue by molant** [webhintio/webhint-ado-extension#11]
Based on [this StackOverflow answer](https://stackoverflow.com/questions/56029313/how-to-test-new-azure-devops-extension-version-before-publishing-it-for-everyone) it looks like we have to publish every time we want to test a change and that if we want to avoid releasing to everybody that already uses it we should use different names, etc.

We should have a script that bumps the version and changes the required IDs to whatever needs to be depending on where we are publishing.

@mamichae @danlope @vinodkumarys do you know if there's an easier way to test this or a script that already does this (or something similar)?

**Comment by molant** [comment]
Based on [this StackOverflow answer](https://stackoverflow.com/questions/56029313/how-to-test-new-azure-devops-extension-version-before-publishing-it-for-everyone) it looks like we have to publish every time we want to test a change and that if we want to avoid releasing to everybody that already uses it we should use different names, etc.

We should have a script that bumps the version and changes the required IDs to whatever needs to be depending on where we are publishing.

@mamichae @danlope @vinodkumarys do you know if there's an easier way to test this or a script that already does this (or something similar)?

**Comment by danlope** [comment]
I am not aware of an easier way. I'll keep you updated if a solution comes up.

**Comment by molant** [comment]
For now I'm using `tfx extension publish --token PAT` but even with that the experience is quite painful.

I'm still not up to date with all the versioning that is going on in the extension. It looks like the extension version is going to increment each time I create it otherwise the store will not accept it, correct? What about the task? From my tests it looks like I also have to increase the version or otherwise an old version will be used?

![image](https://user-images.githubusercontent.com/606594/67830488-0c4f3000-fa98-11e9-8d19-98fffa799387.png)
