### ISSUE TITLE
Look into flattening the structure

### ISSUE THREAD

**Issue by molant** [webhintio/webhint-ado-extension#5]
Right now the project structure looks like this:

![image](https://user-images.githubusercontent.com/606594/67526696-2f2dae80-f66a-11e9-8d4c-c4b669152844.png)

We can probably move the contents of `WebhintV1` into the root.

@mamichae @danlope @vinodkumarys is there any known limitation for this?

**Comment by danlope** [comment]
Nothing that I am aware of. We chose WebhintV1 to follow a convention just in case we wanted to create an updated version later on.
